### ISSUE TITLE
Dlib Lilibrary is not installing in my system

### ISSUE THREAD

**Issue by thisisdipen** [akshaybahadur21/Facial-Recognition-using-Facenet#1]
I was trying to compiled your project but it's getting error or TensorFlow and Segmentation fault in both version of python, I've Install each and every Requirements of this module including Tensorflow module, 
Have a look of error
![deepinscreenshot_deepin-terminal_20180521195313](https://user-images.githubusercontent.com/26856382/40312612-f9304c44-5d30-11e8-9654-ab15f2360bd1.png)

**Comment by akshaybahadur21** [comment]
Few steps:
Make sure that your python version is 3.6.
Not sure if the problem is with dlib as far as I can see, the problem is with load_model which is a  keras utility.
You can check here for more info:

Installing dlib : https://www.pyimagesearch.com/2017/03/27/how-to-install-dlib/
Bad marshall error : https://github.com/keras-team/keras/issues/7440
